dd<-read.csv2("COMRECT.csv")
dd$M<-as.factor(dd$M)
#options(contrasts = c("contr.sum", "contr.treatment"))
options(contrasts = c("contr.helmert", "contr.treatment"))
library(lsmeans)
library(car)
names(dd)
head(dd)
with(data=dd,scatterplot(C,V,group=M,smooth=F))
mv<-lm(V~M+C+M:C,dd)
plot(fitted(mv),resid(mv))
abline(h=0,lty=2)
#plot(mv,ask=F)
Anova(mv,ty=3)
(lsm<-lsmeans(mv,~M|C,at=list(C=c(90,105,120))))
pairs(lsm)
(lsmp<-lsmeans(mv,~M,trend="C"))
pairs(lsmp)
mv2<-lm(V~M+C,dd)
plot(fitted(mv2),resid(mv2))
abline(h=0,lty=2)
#plot(mv2,ask=F)
Anova(mv2,ty=3)
(lsm2<-lsmeans(mv2,~M|C,at=list(C=c(90,105,120))))
pairs(lsm2)


with(data=dd,scatterplot(C,VV,group=M,smooth=F))
abline(v=c(90,100,110,120,130),lty=2,col="blue")
mvv<-lm(VV~M+C+M:C,dd)
plot(fitted(mvv),resid(mvv))
abline(h=0,lty=2)
#plot(mvv,ask=F)
Anova(mvv,ty=3)
(lsmvv<-lsmeans(mvv,~M|C,at=list(C=c(90,100,110,120,130))))
pairs(lsmvv)
(lsmpvv<-lsmeans(mvv,~M,trend="C"))
pairs(lsmpvv)
